### PR TITLE
added posibility to use a different hashfunction

### PR DESCRIPTION
**Pull request by c7h**
sometimes it's useful to have a different hashfunction like sha-512 instead of the default sha-1

### CODE REVIEW

**Comment by gingerlime** [comment]
Thanks for your contribution @c7h. Are you aware of any implementations that use a different hash function? As far as I can tell from the [rfc](http://tools.ietf.org/html/rfc4226) - HOTP/TOTP rely on HMAC-SHA-1 only, so any such implementation would be non-standard...

As far as your implementation, I didn't personally like passing an integer representing the sha variation. I would much rather pass in the hash function itself. This is similar to the `digestmod` param to `hmac`...

So implementation-wise - it will be more modular to do something like

```python
def HOTP(K, C, digits=6, digestmod=hashlib.sha1):
    # ...
    hmac = hmac.new(key=K, msg=C_bytes, digestmod=digestmod).hexdigest()
```

Irrespective of implementation, I'd like to make sure that hotpie provides standards-compliant way as the first priority.

**Comment by c7h** [comment]
yeah you are right, it's not part of the RFC. In fact it's a non-standard implementation. If you would keep your implementation 'clean'  you shouldn't merge this request.

**Comment by gingerlime** [comment]
I looked into this, and seems like [rfc6238](http://tools.ietf.org/html/rfc6238) actually mentions SHA-256 and SHA-512, although it's a bit odd considering that [rfc4226](http://tools.ietf.org/html/rfc4226), which it's based on -- doesn't...

See http://security.stackexchange.com/q/45904/7306

I have therefore implemented this in 7d8500d3e4f1ef3abb7dcde9e100886ad12f0e39, and used the test vectors in rfc6238 - seems to work ok. Would be great if you can take a look / test if it works for you.

**Comment by gingerlime** [comment]
btw, I think this comment on the stackexchange question I linked is valid:

> Furthermore, I wonder what would be the idea behind this: the implementation calls for the result of the HMAC to be truncated and the initial HMAC uses a very short secret: using a different hash algorithm here wouldn't improve security but it would make it incompatible with existing applications and tokens.

Since HOTP is truncating the output anyway, and HMAC is robust even against collisions in SHA-1 (see [Appendix B of rfc 4226](http://tools.ietf.org/html/rfc4226#page-25)), then I can't actually see any practical security improvement by using sha-256 or sha-512 here to be honest.

From B.3.  HOTP Status:
> Since no new weakness has surfaced in HMAC-SHA-1, there is no impact
   on HOTP.  The best attacks on HOTP remain those described in the
   document, namely, to try to guess output values.

>   The security proof of HOTP requires that HMAC-SHA-1 behave like a
   pseudorandom function.  The quality of HMAC-SHA-1 as a pseudorandom
   function is not impacted by the new attacks on SHA-1, and so neither
   is this proven guarantee.

**Pull request closed without merging**
